
p_a = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']
p_b = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']
p_c = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']
p_d = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']
p_e = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']
p_f = ['OKE', 'MCD', 'JD', 'MET', 'STX', 'DFS', 'TTD', 'CME', 'IRBT', 'ED', 'MAS', 'COIN', 'BRK.B', 'VZ', 'TTWO', 'QNCX', 'WMT', 'ASTR', 'LOW', 'TSLA', 'MSTR', 'BXP', 'IVZ', 'APA', 'ZM', 'RCL', 'BAC', 'OVV', 'AMAT', 'EHTH', 'DIS', 'ANAB', 'AAPL', 'ROST', 'CFG', 'BKNG', 'EXPE', 'NEE', 'MAR', 'SCHW', 'OXY', 'MDT', 'PFGC', 'NFLX', 'EVH', 'INTC', 'MOS', 'INCY', 'SRPT', 'KHC', 'CLOV', 'TRIP', 'GD', 'GOOGL', 'DVN', 'MTCH', 'ETRN', 'ACH', 'PG', 'SMAR', 'META', 'WDC', 'CHX', 'PAGS', 'HLT', 'GPS', 'TTM', 'RACE', 'GILD', 'CLF', 'PINS', 'ARWR', 'ACAD', 'M', 'BIDU', 'CNC', 'GTHX', 'LPL', 'IDXX', 'CPRI', 'ROKU', 'ORCL', 'SPR', 'CHEF', 'PPC', 'TSM', 'F', 'GLW', 'MDLZ', 'FSLY', 'LHX', 'CTXS', 'ABBV', 'SQ', 'VTR', 'AMGN', 'WYNN', 'EA', 'UNH', 'PPL', 'LVS', 'LI', 'YY', 'EBAY', 'PTR', 'RL', 'NVAX', 'SPG', 'H', 'SNY', 'HA', 'INGR', 'ETSY', 'DXC', 'HEAR', 'JPM', 'PBI', 'HD', 'MED', 'NET', 'SWN', 'CNK', 'MO', 'W', 'SNAP', 'PBF', 'RRC', 'TSN', 'BKR', 'AA', 'KMI', 'AMT', 'COTY', 'BALL', 'WELL', 'PSX', 'REGI', 'HPQ', 'KO', 'MLCO', 'RRGB', 'PM', 'EQT', 'UBER', 'COP', 'GRMN', 'IBN', 'RKLB', 'WM', 'QCOM', 'ILMN', 'MOMO', 'MDB', 'WRK', 'BJRI', 'TWLO', 'TXN', 'UAL', 'MPC', 'SPGI', 'PLTR', 'HOG', 'AXP', 'GOOG', 'PRU', 'BEN', 'TDOC', 'TMUS', 'GS', 'MA', 'AIG', 'OMC', 'WB', 'BILI', 'TER', 'SBUX', 'CAT', 'PYPL', 'CVS', 'HCA', 'UPS', 'WFC', 'FDX', 'SIG', 'HIG', 'RIOT', 'CHGG', 'YUM', 'MS', 'NDAQ', 'SEDG', 'HPE', 'Z', 'SPCE', 'SPOT', 'ARE', 'MFGP', 'XOM', 'IOVA', 'PVH', 'ALK', 'SLB', 'TROW', 'NTES', 'TAK', 'PARA', 'WKHS', 'DAL', 'MSFT', 'DHI', 'ET', 'VRTX', 'BABA', 'HAS', 'EIX', 'ALB', 'KEY', 'BFH', 'LYB', 'DRI', 'BSX', 'WMB', 'PLUG', 'VALE', 'QRVO', 'HON', 'LMT', 'BYND', 'DOCU', 'LUV', 'LEVI', 'LYFT', 'CAH', 'MAC', 'AMD', 'PUMP', 'RF', 'USB', 'JNJ', 'SHI', 'KR', 'TJX', 'DOW', 'MNST', 'BUD', 'NXPI', 'CMCSA', 'CCL', 'UPWK', 'ADBE', 'KMB', 'USFD', 'ATRA', 'ZYXI', 'MU', 'ATVI', 'HAL', 'LRCX', 'BA', 'T', 'REGN', 'RTX', 'CVX', 'AERI', 'PCG', 'AYX', 'GPN', 'HBAN', 'V', 'NVDA', 'CLR', 'WU', 'ZYNE', 'MARA', 'EOG', 'HRTX', 'SNPS', 'BTI', 'NKE', 'PLAY', 'EPAM', 'ADM', 'JWN', 'CRM', 'TGT', 'VLO', 'BMY', 'VIPS', 'CORR', 'CNP', 'OII', 'TWTR', 'ABMD', 'BK', 'GT', 'ZS', 'BIIB', 'DHR', 'ADSK', 'SO', 'D', 'XRX', 'SAGE', 'SYY', 'UAA', 'CINF', 'VREX', 'HII', 'NTNX', 'MRNA', 'BYSI', 'CLSK', 'AVGO', 'CRWD', 'NEM', 'TTE', 'EMR', 'GM', 'MMM', 'EAR', 'NRG', 'DDOG', 'TWOU', 'FSLR', 'C', 'BBY', 'SAVE', 'ABT', 'LFC', 'IRM', 'DXCM', 'WBA', 'ACN', 'PEP', 'LLY', 'ENPH', 'NTAP', 'PTON', 'GOSS', 'LTHM', 'CSCO', 'FCX']




p1_a = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'PLTR', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP', 'SMAR', 'DXC', 'PPC', 'EVC', 'WMB', 'HPQ', 'DAL', 'USFD', 'BAC', 'APA', 'CLW', 'SLB', 'HOG', 'SPR', 'GM', 'PLAY', 'SAGE', 'BYND', 'LVS', 'Z', 'NRG', 'RCL', 'BSX', 'CFG', 'LI', 'WBA', 'KHC', 'EQT', 'CHEF', 'TWTR', 'INTC', 'TDOC', 'IRBT', 'WRK', 'UAL', 'LUV', 'BTI' , 'BFH', 'IRBT', 'BK', 'ALK', 'CMCSA', 'WFC', 'MO', 'ARWR', 'EQT', 'CSCO', 'VZ', 'KR', 'TTD', 'NEM', 'EBAY', 'AYX', 'IRM', 'PTR', 'NET', 'USB', 'CPRI', 'WDC', 'OVV', 'SNY', 'W', 'PFGC', 'MOS', 'TTE', 'AIG', 'C', 'VTR', 'DOW', 'MAS', 'BUD', 'NVAX', 'CAH', 'SIG', 'COIN', 'DVN', 'PVH', 'OKE', 'TJX', 'GILD', 'MET', 'REGI', 'MU', 'OXY', 'MDLZ', 'KO', 'JD', 'WYNN', 'EIX', 'DOCU', 'SCHW', 'HIG', 'CLR', 'OMC', 'NTAP', 'MTCH', 'BALL', 'BBY', 'SO', 'SQ', 'BMY', 'ORCL', 'HAS', 'STX', 'DHI', 'ROST', 'D', 'ADM', 'ATVI', 'INCY', 'FSLR', 'NEE', 'SBUX', 'MS', 'H', 'TWLO']

p2_a = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']
p2_b = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']
p2_c = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']
p2_d = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']
p2_e = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']
p2_f = ['EHTH', 'CCL', 'UAA', 'GPS', 'MAC', 'PUMP', 'ACH', 'ET', 'VIPS', 'OKE', 'PTON', 'PCG', 'OII', 'PAGS', 'GT', 'F', 'HBAN', 'IOVA', 'TWOU', 'HPE', 'LYFT', "HEAR", "SNAP", "TAK", "XRX", 'NTNX', 'HA', 'CLF', 'PLUG', 'ACAD',  'SHI', 'IVZ', 'M', 'WU', 'M', 'CNK', 'KMI', 'TRIP', 'LEVI', 'KEY', 'CHX', 'IBN', 'CHGG', 'RF', 'WB', 'JWN', 'LTHM', 'PINS', 'ANAB', 'T', 'UPWK', 'UBER', 'VREX', 'BJRI', 'BILI', 'SAVE', 'BEN', 'PARA', 'YY', 'FCX', 'BKR', 'RRC', 'TTM', 'HAL', 'CNP']


snp_b2 = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']
snp_b2a = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']
snp_b2b = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']
snp_b2c = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']
snp_b2d = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']
snp_b2e = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH']

snp_b_15_2 = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15_2a = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15_2b = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU',  'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15_2c = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU',  'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15_2d = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15_2e = ['GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']

snp_b_15 = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15a = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15b = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15c = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15d = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']
snp_b_15e = ['COTY', 'CCL', 'JWN', 'DXC', 'HAL', 'SLB', 'RCL', 'BFH', 'DVN', 'OXY', 'WYNN', 'PVH', 'GPS', 'XRX', 'BKR', 'PARA', 'FCX', 'ALK', 'WDC', 'C', 'MOS', 'OKE', 'DHI', 'BBY', 'MPC', 'AMD', 'PRU', 'EXPE', 'EOG', 'VLO', 'MAR', 'HCA', 'ALB']



snp_b_13_15 = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']
snp_b_13_15a = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']
snp_b_13_15b = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']
snp_b_13_15c = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']
snp_b_13_15d = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']
snp_b_13_15e = ['KEY', 'WVB', 'BAC', 'LVS', 'UAL', 'HOG', 'CFG', 'ALK', 'MAS', 'BBY', 'EMR', 'PSX', 'MS', 'LYB', 'RTX', 'RL', 'COP', 'AMAT', 'QRVO', 'SPG', 'DRI', 'BA', 'META', 'NVDA', 'FDX', 'ADSK', 'ABMD', 'GS']



snp_b_11_13 = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']
snp_b_11_13a = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']
snp_b_11_13b = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']
snp_b_11_13c = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']
snp_b_11_13d = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']
snp_b_11_13e = ['UAA', 'HBAN', 'HPE', 'IVZ', 'KEY', 'RF', 'BEN', 'WMB', 'DAL', 'GM', 'WRK', 'WFC', 'EBAY', 'VTR', 'AIG', 'MU', 'MET', 'NTAP', 'SYY', 'BXP', 'MNST', 'XOM', 'PYPL', 'DIS', 'TROW', 'HLT', 'QCOM', 'CVX', 'AAPL', 'HON', 'UPS', 'LOW', 'ACN', 'SNPS', 'LRCX', 'BKNG']

snp_b_09_11 = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']
snp_b_09_11a = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']
snp_b_09_11b = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']
snp_b_09_11c = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']
snp_b_09_11d = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']
snp_b_09_11e = ['F', 'WU', 'KMI', 'CNP', 'HPQ', 'GLW', 'KHC', 'LUV', 'CMCSA', 'NRG', 'BK', 'CSCO', 'USB', 'TJX', 'CAH', 'HIG', 'SCHW', 'HAS', 'WELL', 'DXCM', 'ROST', 'GRMN', 'NKE', 'YUM', 'GOOGL', 'JPM', 'GOOG', 'GPN', 'MMM', 'AXP', 'TGT', 'TXN', 'CRM', 'NDAQ', 'CAT', 'ILMN', 'V', 'GD', 'NFLX', 'MSFT', 'HD', 'MA', 'SPGI', 'IDXX', 'ADBE', 'AVGO']

b_15_plus = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']
b_15_plus_a = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']
b_15_plus_b = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']
b_15_plus_c = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']
b_15_plus_d = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']
b_15_plus_e = ['ACH', 'OII', 'ETRN', 'RIOT', 'GPS', 'CCL', 'MAC', 'ET', 'GTHX', 'GT', 'PAGS', 'HA', 'CNK', 'NTNX', 'MARA', 'XRX', 'UPWK', 'CLF', 'M', 'CHX', 'JWN', 'BKR', 'PARA', 'BJRI', 'DXC', 'HAL', 'PLUG', 'LTHM', 'TTM', 'FCX', 'USDF', 'RRC', 'SPR', 'CHEF', 'APA', 'PBF', 'EVH', 'SLB', 'SMAR', 'RCL', 'SAGE', 'PLAY', 'BFH', 'ALK', 'WDC', 'OVV', 'CPRI', 'AA', 'C', 'MOS', 'OKE', 'DVN', 'OXY', 'CLR', 'SIG', 'WYNN', 'W', 'PVH', 'TTD', 'BBY', 'DHI', 'ROKU', 'SQ', 'MPC', 'AMD', 'PRU', 'DFS', 'EXPE', 'VLO', 'EOG', 'ETSY', 'SPOT', 'MAR', 'HCA', 'ALB', 'MSTR', 'EPAM', 'TSLA']


if __name__ == '__main__':
    print(len(p_a))